# Generated by Django 5.1.6 on 2025-04-18 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('max_active_jobs', models.PositiveIntegerField(default=1, help_text='Maximum number of jobs a company can have active at once.')),
                ('can_feature_jobs', models.BooleanField(default=False, help_text='Can jobs be marked as featured?')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['price'],
            },
        ),
    ]
