# Generated by Django 5.1.6 on 2025-04-21 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='can_feature_jobs',
        ),
        migrations.AddField(
            model_name='plan',
            name='currency',
            field=models.CharField(default='€', max_length=3),
        ),
        migrations.AddField(
            model_name='plan',
            name='has_company_dashboard',
            field=models.BooleanField(default=True, help_text='Does this plan include access to the company dashboard?'),
        ),
        migrations.AddField(
            model_name='plan',
            name='has_cv_access',
            field=models.BooleanField(default=False, help_text='Does this plan allow access to candidate CVs?'),
        ),
        migrations.AddField(
            model_name='plan',
            name='has_priority_support',
            field=models.BooleanField(default=False, help_text='Does this plan include priority support?'),
        ),
        migrations.AddField(
            model_name='plan',
            name='is_featured',
            field=models.BooleanField(default=False, help_text="Mark this plan as 'Popular' or featured."),
        ),
        migrations.AddField(
            model_name='plan',
            name='is_promoted_only',
            field=models.BooleanField(default=False, help_text='Is this a special plan only for promoting existing jobs?'),
        ),
        migrations.AddField(
            model_name='plan',
            name='promoted_jobs_limit',
            field=models.PositiveIntegerField(default=0, help_text='Maximum number of jobs that can be promoted simultaneously.'),
        ),
        migrations.AddField(
            model_name='plan',
            name='visibility_days',
            field=models.PositiveIntegerField(default=30, help_text='Number of days a job posting remains visible.'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Allow disabling plans from being selected.'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='max_active_jobs',
            field=models.PositiveIntegerField(default=1, help_text='Maximum number of jobs a company can have active at once. Use 0 for unlimited (handle in logic).'),
        ),
    ]
