# Generated by Django 5.1.6 on 2025-04-23 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_companyprofile_location_and_more'),
        ('payments', '0002_remove_plan_can_feature_jobs_plan_currency_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Plan',
            new_name='SubscriptionPlan',
        ),
        migrations.CreateModel(
            name='CompanySubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, help_text='Date when the subscription expires. Null for non-expiring plans.', null=True)),
                ('is_active', models.BooleanField(default=False, help_text='Is the subscription currently active?')),
                ('stripe_subscription_id', models.CharField(blank=True, help_text='Stripe Subscription ID for recurring payments.', max_length=255, null=True)),
                ('stripe_payment_intent_id', models.CharField(blank=True, help_text='Stripe Payment Intent ID for one-time payments.', max_length=255, null=True)),
                ('stripe_session_id', models.CharField(blank=True, help_text='Stripe Checkout Session ID used for the purchase.', max_length=255, null=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='accounts.companyprofile')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_subscriptions', to='payments.subscriptionplan')),
            ],
            options={
                'verbose_name': 'Company Subscription',
                'verbose_name_plural': 'Company Subscriptions',
                'ordering': ['-start_date'],
            },
        ),
    ]
