# Generated by Django 5.1.6 on 2025-04-23 16:26

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='location',
        ),
        migrations.AddField(
            model_name='job',
            name='city',
            field=models.CharField(default=1, max_length=100, verbose_name='Oraș'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='country',
            field=django_countries.fields.CountryField(default='RO', max_length=2),
        ),
    ]
