# Generated by Django 5.1.6 on 2025-04-25 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_jobreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='description',
        ),
        migrations.AddField(
            model_name='job',
            name='experience_level',
            field=models.CharField(blank=True, choices=[('entry', 'Entry-Level (< 2 ani)'), ('mid', 'Mid-Level (2-5 ani)'), ('senior', 'Senior-Level (5+ ani)'), ('manager', 'Manager / Director'), ('intern', 'Intern / Stagiar'), ('no_experience', 'Fără experiență')], max_length=20, null=True, verbose_name='Nivel Experiență'),
        ),
        migrations.AddField(
            model_name='job',
            name='ideal_candidate',
            field=models.TextField(blank=True, null=True, verbose_name='Candidatul Ideal'),
        ),
        migrations.AddField(
            model_name='job',
            name='positions_available',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Număr Poziții Deschise'),
        ),
        migrations.AddField(
            model_name='job',
            name='responsibilities',
            field=models.TextField(blank=True, null=True, verbose_name='Descrierea jobului / Responsabilități'),
        ),
        migrations.AddField(
            model_name='job',
            name='slug',
            field=models.SlugField(blank=True, help_text='Leave blank to auto-generate from title.', max_length=270),
        ),
        migrations.AddField(
            model_name='job',
            name='what_we_offer',
            field=models.TextField(blank=True, null=True, verbose_name='Ce oferim?'),
        ),
    ]
