# Generated by Django 5.1.6 on 2025-04-25 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_remove_job_description_job_experience_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='slug',
            field=models.SlugField(blank=True, help_text='Leave blank to auto-generate from title.', max_length=270, unique=True),
        ),
    ]
