# Generated by Django 5.0.6 on 2024-07-26 11:58

from django.db import migrations
from django.utils.text import slugify

def populate_categories(apps, schema_editor):
    Category = apps.get_model('jobs', 'Category')
    categories = [
        "Vânzători de produse și servicii",
        "Muncitori în ferme și creșterea animalelor",
        "Bone (îngrijire copii) și menajere (gospodărie)",
        "Reprezentanți relații cu clienții (call-center, suport)",
        "Croitori și confecționeri de textile",
        "Frizeri, cosmeticieni și tehnicieni în înfrumusețare",
        "Formatori și instructori de cursuri",
        "Organizatori de evenimente și animatori",
        "Contabili și specialiști financiar-contabili",
        "Muncitori în construcții și meseriași (zidar, tâmplar, electrician)",
        "Tehnicieni IT și specialiști telecom",
        "Casieri și lucrători în vânzări retail",
        "Lucrători în producție, depozit și logistică",
        "Specialiști marketing, PR și comunicare",
        "Lucrători sezoniere și permanente în străinătate",
        "Agenti de pază și protecție",
        "Personal administrativ și secretariat",
        "Personal hotelier (recepție, housekeeping) și restaurant (chelneri, bucătari)",
        "Personal medical și auxiliar sanitar",
        "Specialiști resurse umane (recrutare, salarizare)",
        "Șoferi (transport marfă/persoane) și mecanici auto",
        "Alte meserii neclasificate",
        "Manageri și administratori de afaceri",
    ]

    for category_name in categories:
        base_slug = slugify(category_name)
        slug = base_slug
        counter = 1
        # Ensure slug uniqueness within this migration
        while Category.objects.filter(slug=slug).exists():
            slug = f"{base_slug}-{counter}"
            counter += 1
        # Use get_or_create with the unique slug
        Category.objects.get_or_create(name=category_name, defaults={'slug': slug})


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_alter_job_slug'),
    ]

    operations = [
        migrations.RunPython(populate_categories),
    ]
