# Generated by Django 5.1.6 on 2025-05-06 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_populate_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='experience_level',
            field=models.CharField(choices=[('entry', 'Entry-Level (< 2 ani)'), ('mid', 'Mid-Level (2-5 ani)'), ('senior', 'Senior-Level (5+ ani)'), ('manager', 'Manager / Director'), ('intern', 'Intern / Stagiar'), ('no_experience', 'Fără experiență')], default=1, max_length=20, verbose_name='Nivel Experiență'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='positions_available',
            field=models.PositiveIntegerField(default=1, verbose_name='Număr Poziții Deschise'),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary_currency',
            field=models.CharField(choices=[('RON', 'RON (Leu Românesc)'), ('EUR', 'EUR (Euro)'), ('USD', 'USD (Dolar American)'), ('GBP', 'GBP (Liră Sterlină)')], default='RON', max_length=3),
        ),
    ]
