# Generated by Django 5.1.6 on 2025-07-20 19:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contactinfo_faq'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titlu')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('excerpt', models.TextField(help_text='Scurt rezumat al articolului (max 300 caractere)', max_length=300, verbose_name='Rezumat')),
                ('content', models.TextField(verbose_name='Conținut')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='articles/', verbose_name='Imagine principală')),
                ('is_published', models.BooleanField(default=False, verbose_name='Publicat')),
                ('is_featured', models.BooleanField(default=False, help_text='Articolele evidențiate apar pe prima pagină', verbose_name='Articol evidențiat')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creat la')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizat la')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Publicat la')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Articol',
                'verbose_name_plural': 'Articole',
                'ordering': ['-created_at'],
            },
        ),
    ]
