# Generated by Django 5.1.6 on 2025-04-23 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_companyprofile_location_and_more'),
        ('jobs', '0003_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='saved_jobs',
            field=models.ManyToManyField(blank=True, related_name='saved_by_seekers', to='jobs.job'),
        ),
    ]
