# Generated by Django 5.1.6 on 2025-07-20 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_companyprofile_company_name_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('job_seeker', 'Candidat'), ('company', 'Companie')], default='job_seeker', max_length=20),
        ),
    ]
